name: TensorFlow Lite Converter Issue
about:: Use this template for reporting issues during model conversion to TFLite
labels: 'TFLiteConverter'
body:
  - type: markdown
    attributes:
      label: 1. System information
      value: |
        - OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
        - TensorFlow installation (pip package or built from source):
        - TensorFlow library (version, if pip package or github SHA, if built from source):
    validations:
      required: true

  - type: dropdown
    id: tf-lite-code
    attributes:
      label: 2. Code
      description: Provide code to help us reproduce your issues using one of the following options
        - "Option A:Reference [TensorFlow Model Colab]"
        - "Option B:Reference [TensorFlow Lite Model Colab]"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        You can collect some of this information using our [environment capture script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh). You can also obtain the TensorFlow version with the following: <br> 1. TensorFlow 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` <br>2. TensorFlow 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
  - type: textarea
    id: what-happened
    attributes:
      label: Current behavior?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: code-to-reproduce
    attributes:
      label: Standalone code to reproduce the issue
      description: Provide a reproducible test case that is the bare minimum necessary to generate the problem. Please share a link to Colab, Jupyter, or any notebook.
      placeholder: Tell us what you see!
      value:
      render: shell
    validations:
      required: true
  - type: textarea
    id: code-to-reproduce
    attributes:
      label: 1. Reference TensorFlow Model Colab: Demonstrate how to build your TF model. 2. Reference TensorFlow Lite Model Colab: Demonstrate how to convert your TF model to a TF Lite model (with quantization, if used) and run TFLite Inference (if possible).
      description: (You can paste links or attach files by dragging & dropping them below)
                    - Provide links to your updated versions of the above two colab notebooks.
                    - Provide links to your TensorFlow model and (optionally) TensorFlow Lite Model.
      render: shell
    validations:
      required: true  
